insert into hofs (id, name) values (1, 'Alphazap');
insert into hofs (id, name) values (2, 'Y-Solowarm');
insert into hofs (id, name) values (3, 'Home Ing');
insert into hofs (id, name) values (4, 'Bitwolf');
insert into hofs (id, name) values (5, 'Stronghold');
insert into hofs (id, name) values (6, 'Gembucket');
insert into hofs (id, name) values (7, 'Otcom');
insert into hofs (id, name) values (8, 'Fix San');
insert into hofs (id, name) values (9, 'Stim');
insert into hofs (id, name) values (10, 'Hatity');
insert into hofs (id, name) values (11, 'Matsoft');
insert into hofs (id, name) values (12, 'Home Ing');
insert into hofs (id, name) values (13, 'Cardguard');
insert into hofs (id, name) values (14, 'Stringtough');
insert into hofs (id, name) values (15, 'Subin');
insert into hofs (id, name) values (16, 'Voltsillam');
insert into hofs (id, name) values (17, 'Veribet');
insert into hofs (id, name) values (18, 'Overhold');
insert into hofs (id, name) values (19, 'Wrapsafe');
insert into hofs (id, name) values (20, 'Gembucket');
insert into hofs (id, name) values (21, 'Mat Lam Tam');
insert into hofs (id, name) values (22, 'Keylex');
insert into hofs (id, name) values (23, 'Sub-Ex');
insert into hofs (id, name) values (24, 'Opela');
insert into hofs (id, name) values (25, 'Rank');
insert into hofs (id, name) values (26, 'Cookley');
insert into hofs (id, name) values (27, 'Temp');
insert into hofs (id, name) values (28, 'Fixflex');
insert into hofs (id, name) values (29, 'Kanlam');
insert into hofs (id, name) values (30, 'Namfix');
insert into hofs (id, name) values (31, 'Tampflex');
insert into hofs (id, name) values (32, 'Andalax');
insert into hofs (id, name) values (33, 'Keylex');
insert into hofs (id, name) values (34, 'Sonair');
insert into hofs (id, name) values (35, 'Stim');
insert into hofs (id, name) values (36, 'Job');
insert into hofs (id, name) values (37, 'Mat Lam Tam');
insert into hofs (id, name) values (38, 'Subin');
insert into hofs (id, name) values (39, 'Lotlux');
insert into hofs (id, name) values (40, 'Rank');
insert into hofs (id, name) values (41, 'Transcof');
insert into hofs (id, name) values (42, 'Zaam-Dox');
insert into hofs (id, name) values (43, 'Zontrax');
insert into hofs (id, name) values (44, 'Span');
insert into hofs (id, name) values (45, 'Transcof');
insert into hofs (id, name) values (46, 'Gembucket');
insert into hofs (id, name) values (47, 'Daltfresh');
insert into hofs (id, name) values (48, 'Greenlam');
insert into hofs (id, name) values (49, 'Job');
insert into hofs (id, name) values (50, 'Fix San');
