insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (1, 'It', 98, 'Structural and Misc Steel (Fabrication)', 'It', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'https://php.net/morbi/vel.html?sed=justo&accumsan=sit&felis=amet&ut=sapien&at=dignissim&dolor=vestibulum&quis=vestibulum&odio=ante&consequat=ipsum&varius=primis&integer=in&ac=faucibus&leo=orci&pellentesque=luctus&ultrices=et&mattis=ultrices&odio=posuere&donec=cubilia&vitae=curae&nisi=nulla&nam=dapibus&ultrices=dolor&libero=vel&non=est&mattis=donec&pulvinar=odio&nulla=justo&pede=sollicitudin&ullamcorper=ut&augue=suscipit&a=a&suscipit=feugiat&nulla=et&elit=eros&ac=vestibulum&nulla=ac&sed=est&vel=lacinia&enim=nisi&sit=venenatis&amet=tristique&nunc=fusce&viverra=congue&dapibus=diam&nulla=id&suscipit=ornare&ligula=imperdiet&in=sapien&lacus=urna&curabitur=pretium&at=nisl&ipsum=ut&ac=volutpat&tellus=sapien&semper=arcu&interdum=sed&mauris=augue&ullamcorper=aliquam&purus=erat&sit=volutpat&amet=in&nulla=congue&quisque=etiam&arcu=justo&libero=etiam&rutrum=pretium&ac=iaculis&lobortis=justo&vel=in&dapibus=hac&at=habitasse', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (2, 'Cardguard', 4, 'RF Shielding', 'Fixflex', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'http://umich.edu/porta/volutpat/erat/quisque.jsp?rutrum=erat&rutrum=nulla&neque=tempus&aenean=vivamus&auctor=in&gravida=felis&sem=eu&praesent=sapien&id=cursus&massa=vestibulum&id=proin&nisl=eu&venenatis=mi&lacinia=nulla', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (3, 'Opela', 99, 'Granite Surfaces', 'Trippledex', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'http://icio.us/scelerisque/quam/turpis.aspx?leo=purus&pellentesque=eu&ultrices=magna&mattis=vulputate&odio=luctus&donec=cum&vitae=sociis&nisi=natoque&nam=penatibus&ultrices=et&libero=magnis&non=dis&mattis=parturient&pulvinar=montes&nulla=nascetur&pede=ridiculus&ullamcorper=mus&augue=vivamus&a=vestibulum&suscipit=sagittis&nulla=sapien&elit=cum&ac=sociis&nulla=natoque&sed=penatibus&vel=et&enim=magnis&sit=dis&amet=parturient&nunc=montes&viverra=nascetur&dapibus=ridiculus&nulla=mus&suscipit=etiam&ligula=vel&in=augue&lacus=vestibulum&curabitur=rutrum&at=rutrum&ipsum=neque&ac=aenean&tellus=auctor&semper=gravida&interdum=sem&mauris=praesent&ullamcorper=id&purus=massa&sit=id&amet=nisl&nulla=venenatis&quisque=lacinia&arcu=aenean&libero=sit&rutrum=amet&ac=justo&lobortis=morbi&vel=ut&dapibus=odio&at=cras&diam=mi&nam=pede&tristique=malesuada&tortor=in&eu=imperdiet', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (4, 'Zaam-Dox', 45, 'Casework', 'Alphazap', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'http://webeden.co.uk/montes/nascetur.js?duis=volutpat&aliquam=eleifend&convallis=donec', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (5, 'Biodex', 28, 'Curb & Gutter', 'Zontrax', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.

Fusce consequat. Nulla nisl. Nunc nisl.', 'https://goo.ne.jp/praesent/lectus.jsp?primis=nascetur&in=ridiculus&faucibus=mus&orci=vivamus&luctus=vestibulum&et=sagittis&ultrices=sapien&posuere=cum&cubilia=sociis&curae=natoque&nulla=penatibus&dapibus=et&dolor=magnis&vel=dis&est=parturient&donec=montes&odio=nascetur&justo=ridiculus&sollicitudin=mus&ut=etiam&suscipit=vel&a=augue&feugiat=vestibulum&et=rutrum&eros=rutrum&vestibulum=neque&ac=aenean&est=auctor&lacinia=gravida&nisi=sem&venenatis=praesent&tristique=id&fusce=massa&congue=id&diam=nisl&id=venenatis&ornare=lacinia&imperdiet=aenean&sapien=sit&urna=amet&pretium=justo&nisl=morbi&ut=ut&volutpat=odio&sapien=cras&arcu=mi&sed=pede&augue=malesuada&aliquam=in&erat=imperdiet&volutpat=et&in=commodo&congue=vulputate&etiam=justo&justo=in&etiam=blandit&pretium=ultrices&iaculis=enim&justo=lorem&in=ipsum&hac=dolor&habitasse=sit&platea=amet&dictumst=consectetuer&etiam=adipiscing&faucibus=elit', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (6, 'Duobam', 56, 'Plumbing & Medical Gas', 'Holdlamis', 'Sed ante. Vivamus tortor. Duis mattis egestas metus.', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.

Aenean lectus. Pellentesque eget nunc. Donec quis orci eget orci vehicula condimentum.', 'http://canalblog.com/a/nibh/in/quis.png?enim=mauris&lorem=non&ipsum=ligula&dolor=pellentesque&sit=ultrices&amet=phasellus&consectetuer=id&adipiscing=sapien&elit=in&proin=sapien&interdum=iaculis&mauris=congue&non=vivamus', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (7, 'Tresom', 98, 'Rebar & Wire Mesh Install', 'Mat Lam Tam', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'http://yandex.ru/donec/posuere/metus.xml?sed=tempus&tincidunt=sit&eu=amet&felis=sem&fusce=fusce&posuere=consequat&felis=nulla&sed=nisl&lacus=nunc&morbi=nisl&sem=duis&mauris=bibendum&laoreet=felis&ut=sed&rhoncus=interdum&aliquet=venenatis&pulvinar=turpis&sed=enim&nisl=blandit&nunc=mi&rhoncus=in&dui=porttitor&vel=pede&sem=justo&sed=eu&sagittis=massa&nam=donec&congue=dapibus&risus=duis&semper=at&porta=velit&volutpat=eu&quam=est&pede=congue&lobortis=elementum&ligula=in&sit=hac&amet=habitasse&eleifend=platea&pede=dictumst&libero=morbi&quis=vestibulum&orci=velit&nullam=id&molestie=pretium&nibh=iaculis&in=diam&lectus=erat&pellentesque=fermentum&at=justo&nulla=nec&suspendisse=condimentum&potenti=neque&cras=sapien&in=placerat&purus=ante&eu=nulla&magna=justo&vulputate=aliquam', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (8, 'Tin', 13, 'RF Shielding', 'Flowdesk', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'Duis consequat dui nec nisi volutpat eleifend. Donec ut dolor. Morbi vel lectus in quam fringilla rhoncus.

Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'http://shop-pro.jp/a/nibh/in/quis/justo/maecenas.jsp?suscipit=aliquet&a=massa&feugiat=id&et=lobortis&eros=convallis&vestibulum=tortor&ac=risus&est=dapibus&lacinia=augue&nisi=vel&venenatis=accumsan', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (9, 'Kanlam', 44, 'Granite Surfaces', 'Cardguard', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.

Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'http://google.ru/odio.json?justo=consectetuer&pellentesque=adipiscing&viverra=elit&pede=proin&ac=interdum&diam=mauris&cras=non&pellentesque=ligula&volutpat=pellentesque&dui=ultrices&maecenas=phasellus&tristique=id&est=sapien&et=in&tempus=sapien&semper=iaculis&est=congue&quam=vivamus&pharetra=metus&magna=arcu&ac=adipiscing&consequat=molestie&metus=hendrerit&sapien=at&ut=vulputate&nunc=vitae&vestibulum=nisl&ante=aenean&ipsum=lectus&primis=pellentesque&in=eget', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (10, 'Fintone', 25, 'Overhead Doors', 'Rank', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'https://sun.com/magna/vulputate/luctus/cum.json?ultrices=sit&mattis=amet&odio=sem&donec=fusce&vitae=consequat&nisi=nulla&nam=nisl&ultrices=nunc&libero=nisl&non=duis&mattis=bibendum&pulvinar=felis&nulla=sed&pede=interdum&ullamcorper=venenatis&augue=turpis&a=enim&suscipit=blandit&nulla=mi&elit=in&ac=porttitor&nulla=pede&sed=justo&vel=eu&enim=massa&sit=donec&amet=dapibus&nunc=duis&viverra=at&dapibus=velit&nulla=eu&suscipit=est&ligula=congue&in=elementum&lacus=in&curabitur=hac&at=habitasse&ipsum=platea&ac=dictumst&tellus=morbi&semper=vestibulum&interdum=velit&mauris=id&ullamcorper=pretium&purus=iaculis&sit=diam&amet=erat&nulla=fermentum&quisque=justo&arcu=nec&libero=condimentum&rutrum=neque&ac=sapien&lobortis=placerat&vel=ante&dapibus=nulla&at=justo&diam=aliquam', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (11, 'Trippledex', 25, 'Marlite Panels (FED)', 'Greenlam', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Proin risus. Praesent lectus.

Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'https://woothemes.com/sed.jpg?duis=pede&faucibus=malesuada&accumsan=in&odio=imperdiet&curabitur=et&convallis=commodo&duis=vulputate&consequat=justo&dui=in&nec=blandit&nisi=ultrices&volutpat=enim&eleifend=lorem&donec=ipsum&ut=dolor&dolor=sit&morbi=amet&vel=consectetuer&lectus=adipiscing&in=elit&quam=proin&fringilla=interdum&rhoncus=mauris&mauris=non&enim=ligula&leo=pellentesque&rhoncus=ultrices&sed=phasellus&vestibulum=id&sit=sapien', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (12, 'It', 12, 'Fire Protection', 'Home Ing', 'Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.

Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'https://cbslocal.com/vel/sem/sed/sagittis/nam/congue/risus.json?nonummy=nisl&maecenas=aenean&tincidunt=lectus&lacus=pellentesque&at=eget&velit=nunc&vivamus=donec&vel=quis&nulla=orci&eget=eget&eros=orci&elementum=vehicula&pellentesque=condimentum&quisque=curabitur&porta=in&volutpat=libero&erat=ut&quisque=massa&erat=volutpat&eros=convallis&viverra=morbi&eget=odio&congue=odio&eget=elementum&semper=eu&rutrum=interdum&nulla=eu&nunc=tincidunt&purus=in&phasellus=leo&in=maecenas&felis=pulvinar&donec=lobortis&semper=est&sapien=phasellus&a=sit&libero=amet&nam=erat&dui=nulla&proin=tempus&leo=vivamus&odio=in&porttitor=felis&id=eu', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (13, 'Voyatouch', 60, 'Casework', 'Viva', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.

Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'http://reference.com/hac/habitasse.xml?amet=posuere&erat=felis&nulla=sed&tempus=lacus&vivamus=morbi&in=sem&felis=mauris&eu=laoreet&sapien=ut&cursus=rhoncus&vestibulum=aliquet&proin=pulvinar&eu=sed&mi=nisl&nulla=nunc&ac=rhoncus&enim=dui&in=vel&tempor=sem&turpis=sed&nec=sagittis&euismod=nam&scelerisque=congue&quam=risus&turpis=semper&adipiscing=porta&lorem=volutpat&vitae=quam&mattis=pede&nibh=lobortis&ligula=ligula&nec=sit&sem=amet&duis=eleifend&aliquam=pede&convallis=libero&nunc=quis&proin=orci&at=nullam&turpis=molestie&a=nibh&pede=in&posuere=lectus&nonummy=pellentesque&integer=at&non=nulla&velit=suspendisse&donec=potenti&diam=cras&neque=in&vestibulum=purus&eget=eu&vulputate=magna&ut=vulputate&ultrices=luctus&vel=cum&augue=sociis&vestibulum=natoque&ante=penatibus&ipsum=et&primis=magnis&in=dis&faucibus=parturient&orci=montes&luctus=nascetur&et=ridiculus&ultrices=mus&posuere=vivamus&cubilia=vestibulum&curae=sagittis&donec=sapien&pharetra=cum', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (14, 'Otcom', 31, 'Doors, Frames & Hardware', 'Lotlux', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.

Phasellus in felis. Donec semper sapien a libero. Nam dui.', 'http://fastcompany.com/velit/nec/nisi/vulputate/nonummy/maecenas/tincidunt.js?vitae=in&ipsum=porttitor&aliquam=pede&non=justo&mauris=eu&morbi=massa&non=donec&lectus=dapibus&aliquam=duis&sit=at&amet=velit&diam=eu&in=est&magna=congue&bibendum=elementum&imperdiet=in&nullam=hac&orci=habitasse&pede=platea&venenatis=dictumst&non=morbi&sodales=vestibulum&sed=velit&tincidunt=id&eu=pretium&felis=iaculis&fusce=diam&posuere=erat&felis=fermentum&sed=justo&lacus=nec&morbi=condimentum&sem=neque&mauris=sapien&laoreet=placerat&ut=ante&rhoncus=nulla&aliquet=justo&pulvinar=aliquam&sed=quis&nisl=turpis&nunc=eget&rhoncus=elit&dui=sodales&vel=scelerisque&sem=mauris&sed=sit', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (15, 'Veribet', 54, 'Curb & Gutter', 'Fixflex', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.

Proin eu mi. Nulla ac enim. In tempor, turpis nec euismod scelerisque, quam turpis adipiscing lorem, vitae mattis nibh ligula nec sem.', 'http://upenn.edu/quam/sapien/varius/ut.json?consequat=eget&in=semper&consequat=rutrum&ut=nulla&nulla=nunc&sed=purus&accumsan=phasellus&felis=in&ut=felis&at=donec&dolor=semper&quis=sapien&odio=a&consequat=libero&varius=nam&integer=dui&ac=proin&leo=leo&pellentesque=odio&ultrices=porttitor&mattis=id&odio=consequat&donec=in&vitae=consequat&nisi=ut&nam=nulla&ultrices=sed&libero=accumsan&non=felis&mattis=ut&pulvinar=at&nulla=dolor&pede=quis&ullamcorper=odio&augue=consequat&a=varius&suscipit=integer', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (16, 'Home Ing', 40, 'Plumbing & Medical Gas', 'Regrant', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'https://google.nl/primis/in/faucibus.xml?hac=orci&habitasse=nullam&platea=molestie&dictumst=nibh&etiam=in&faucibus=lectus&cursus=pellentesque&urna=at&ut=nulla&tellus=suspendisse&nulla=potenti&ut=cras&erat=in&id=purus', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (17, 'Mat Lam Tam', 43, 'Doors, Frames & Hardware', 'Cardguard', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'https://patch.com/et/ultrices/posuere/cubilia/curae/nulla/dapibus.json?quis=lobortis&justo=ligula&maecenas=sit&rhoncus=amet&aliquam=eleifend&lacus=pede&morbi=libero&quis=quis&tortor=orci&id=nullam&nulla=molestie&ultrices=nibh&aliquet=in&maecenas=lectus&leo=pellentesque&odio=at&condimentum=nulla&id=suspendisse&luctus=potenti&nec=cras&molestie=in&sed=purus&justo=eu&pellentesque=magna&viverra=vulputate&pede=luctus&ac=cum&diam=sociis&cras=natoque&pellentesque=penatibus&volutpat=et&dui=magnis&maecenas=dis&tristique=parturient&est=montes&et=nascetur&tempus=ridiculus&semper=mus&est=vivamus&quam=vestibulum&pharetra=sagittis&magna=sapien&ac=cum&consequat=sociis&metus=natoque&sapien=penatibus&ut=et&nunc=magnis&vestibulum=dis&ante=parturient&ipsum=montes&primis=nascetur&in=ridiculus&faucibus=mus&orci=etiam&luctus=vel&et=augue&ultrices=vestibulum&posuere=rutrum&cubilia=rutrum&curae=neque&mauris=aenean&viverra=auctor&diam=gravida&vitae=sem&quam=praesent&suspendisse=id&potenti=massa&nullam=id&porttitor=nisl&lacus=venenatis&at=lacinia&turpis=aenean&donec=sit&posuere=amet&metus=justo&vitae=morbi&ipsum=ut&aliquam=odio&non=cras&mauris=mi&morbi=pede&non=malesuada&lectus=in&aliquam=imperdiet&sit=et&amet=commodo&diam=vulputate&in=justo&magna=in&bibendum=blandit', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (18, 'Trippledex', 29, 'Electrical and Fire Alarm', 'Overhold', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'https://sfgate.com/donec/ut/dolor/morbi/vel/lectus.png?dapibus=justo&duis=sollicitudin&at=ut&velit=suscipit&eu=a&est=feugiat&congue=et&elementum=eros&in=vestibulum&hac=ac&habitasse=est&platea=lacinia&dictumst=nisi&morbi=venenatis&vestibulum=tristique&velit=fusce&id=congue&pretium=diam&iaculis=id&diam=ornare&erat=imperdiet&fermentum=sapien&justo=urna&nec=pretium&condimentum=nisl&neque=ut&sapien=volutpat&placerat=sapien&ante=arcu&nulla=sed&justo=augue&aliquam=aliquam&quis=erat&turpis=volutpat&eget=in&elit=congue&sodales=etiam&scelerisque=justo&mauris=etiam&sit=pretium&amet=iaculis&eros=justo&suspendisse=in&accumsan=hac&tortor=habitasse&quis=platea&turpis=dictumst&sed=etiam&ante=faucibus&vivamus=cursus&tortor=urna&duis=ut&mattis=tellus&egestas=nulla&metus=ut&aenean=erat&fermentum=id&donec=mauris&ut=vulputate&mauris=elementum&eget=nullam&massa=varius&tempor=nulla&convallis=facilisi&nulla=cras&neque=non&libero=velit&convallis=nec&eget=nisi&eleifend=vulputate&luctus=nonummy&ultricies=maecenas&eu=tincidunt&nibh=lacus&quisque=at&id=velit&justo=vivamus&sit=vel&amet=nulla', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (19, 'Konklux', 65, 'Drywall & Acoustical (FED)', 'Fintone', 'Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.', 'Maecenas tristique, est et tempus semper, est quam pharetra magna, ac consequat metus sapien ut nunc. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Mauris viverra diam vitae quam. Suspendisse potenti.

Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'http://hubpages.com/etiam/justo/etiam/pretium/iaculis/justo/in.js?feugiat=quisque&et=erat&eros=eros&vestibulum=viverra&ac=eget&est=congue&lacinia=eget&nisi=semper&venenatis=rutrum&tristique=nulla&fusce=nunc&congue=purus&diam=phasellus&id=in&ornare=felis', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (20, 'Mat Lam Tam', 15, 'Casework', 'Solarbreeze', 'Fusce consequat. Nulla nisl. Nunc nisl.', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.

Morbi porttitor lorem id ligula. Suspendisse ornare consequat lectus. In est risus, auctor sed, tristique in, tempus sit amet, sem.', 'https://guardian.co.uk/faucibus.jsp?congue=gravida&eget=nisi&semper=at&rutrum=nibh&nulla=in&nunc=hac&purus=habitasse&phasellus=platea', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (21, 'Holdlamis', 41, 'Sitework & Site Utilities', 'Solarbreeze', 'Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'http://dmoz.org/a.png?primis=amet&in=eros&faucibus=suspendisse&orci=accumsan&luctus=tortor&et=quis&ultrices=turpis&posuere=sed&cubilia=ante&curae=vivamus&donec=tortor&pharetra=duis&magna=mattis&vestibulum=egestas&aliquet=metus&ultrices=aenean&erat=fermentum&tortor=donec&sollicitudin=ut&mi=mauris&sit=eget&amet=massa&lobortis=tempor&sapien=convallis&sapien=nulla&non=neque&mi=libero&integer=convallis&ac=eget&neque=eleifend&duis=luctus&bibendum=ultricies&morbi=eu&non=nibh', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (22, 'Gembucket', 53, 'RF Shielding', 'Fix San', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.

Phasellus sit amet erat. Nulla tempus. Vivamus in felis eu sapien cursus vestibulum.', 'http://boston.com/sem/fusce.html?justo=convallis&maecenas=tortor&rhoncus=risus&aliquam=dapibus&lacus=augue&morbi=vel&quis=accumsan&tortor=tellus&id=nisi&nulla=eu&ultrices=orci&aliquet=mauris&maecenas=lacinia&leo=sapien&odio=quis&condimentum=libero&id=nullam&luctus=sit&nec=amet&molestie=turpis&sed=elementum&justo=ligula&pellentesque=vehicula&viverra=consequat&pede=morbi&ac=a&diam=ipsum&cras=integer&pellentesque=a&volutpat=nibh&dui=in&maecenas=quis&tristique=justo&est=maecenas&et=rhoncus&tempus=aliquam&semper=lacus&est=morbi&quam=quis', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (23, 'It', 53, 'Ornamental Railings', 'Bytecard', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'https://washington.edu/tellus/nisi/eu/orci/mauris/lacinia.aspx?elementum=elementum&ligula=nullam&vehicula=varius&consequat=nulla&morbi=facilisi&a=cras&ipsum=non&integer=velit&a=nec&nibh=nisi&in=vulputate&quis=nonummy&justo=maecenas&maecenas=tincidunt&rhoncus=lacus&aliquam=at&lacus=velit&morbi=vivamus&quis=vel&tortor=nulla&id=eget&nulla=eros&ultrices=elementum&aliquet=pellentesque&maecenas=quisque&leo=porta&odio=volutpat&condimentum=erat&id=quisque&luctus=erat&nec=eros&molestie=viverra&sed=eget&justo=congue&pellentesque=eget&viverra=semper&pede=rutrum&ac=nulla&diam=nunc&cras=purus&pellentesque=phasellus&volutpat=in&dui=felis&maecenas=donec&tristique=semper&est=sapien&et=a&tempus=libero&semper=nam&est=dui&quam=proin&pharetra=leo&magna=odio&ac=porttitor&consequat=id&metus=consequat&sapien=in&ut=consequat&nunc=ut&vestibulum=nulla&ante=sed&ipsum=accumsan&primis=felis&in=ut&faucibus=at&orci=dolor&luctus=quis&et=odio&ultrices=consequat', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (24, 'Zamit', 48, 'Exterior Signage', 'Keylex', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'http://auda.org.au/libero/nullam/sit.js?nulla=interdum&nisl=venenatis&nunc=turpis&nisl=enim&duis=blandit&bibendum=mi&felis=in&sed=porttitor&interdum=pede&venenatis=justo&turpis=eu&enim=massa&blandit=donec&mi=dapibus&in=duis&porttitor=at&pede=velit&justo=eu&eu=est&massa=congue&donec=elementum&dapibus=in&duis=hac&at=habitasse&velit=platea&eu=dictumst&est=morbi&congue=vestibulum&elementum=velit&in=id&hac=pretium&habitasse=iaculis&platea=diam&dictumst=erat&morbi=fermentum&vestibulum=justo&velit=nec&id=condimentum', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (25, 'Namfix', 63, 'Doors, Frames & Hardware', 'Trippledex', 'Curabitur at ipsum ac tellus semper interdum. Mauris ullamcorper purus sit amet nulla. Quisque arcu libero, rutrum ac, lobortis vel, dapibus at, diam.', 'Sed sagittis. Nam congue, risus semper porta volutpat, quam pede lobortis ligula, sit amet eleifend pede libero quis orci. Nullam molestie nibh in lectus.

Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.', 'https://free.fr/id/ligula/suspendisse/ornare.html?nascetur=gravida&ridiculus=sem&mus=praesent&vivamus=id&vestibulum=massa&sagittis=id&sapien=nisl&cum=venenatis&sociis=lacinia&natoque=aenean&penatibus=sit&et=amet&magnis=justo&dis=morbi&parturient=ut&montes=odio&nascetur=cras', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (26, 'Lotlux', 87, 'Waterproofing & Caulking', 'Zamit', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'https://weibo.com/ante/ipsum/primis/in/faucibus/orci.xml?pretium=orci&iaculis=luctus&justo=et&in=ultrices&hac=posuere&habitasse=cubilia&platea=curae&dictumst=duis&etiam=faucibus&faucibus=accumsan&cursus=odio&urna=curabitur&ut=convallis&tellus=duis&nulla=consequat&ut=dui&erat=nec&id=nisi&mauris=volutpat&vulputate=eleifend&elementum=donec&nullam=ut&varius=dolor&nulla=morbi&facilisi=vel&cras=lectus&non=in&velit=quam&nec=fringilla&nisi=rhoncus&vulputate=mauris&nonummy=enim&maecenas=leo&tincidunt=rhoncus&lacus=sed&at=vestibulum&velit=sit&vivamus=amet&vel=cursus&nulla=id&eget=turpis&eros=integer&elementum=aliquet&pellentesque=massa&quisque=id&porta=lobortis&volutpat=convallis&erat=tortor&quisque=risus', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (27, 'Bigtax', 42, 'Asphalt Paving', 'Opela', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.

Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.

Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.', 'https://meetup.com/purus/aliquet/at/feugiat.json?pellentesque=cubilia&quisque=curae&porta=duis&volutpat=faucibus&erat=accumsan&quisque=odio&erat=curabitur&eros=convallis&viverra=duis&eget=consequat&congue=dui&eget=nec&semper=nisi&rutrum=volutpat&nulla=eleifend&nunc=donec&purus=ut&phasellus=dolor&in=morbi&felis=vel&donec=lectus&semper=in&sapien=quam&a=fringilla&libero=rhoncus&nam=mauris&dui=enim&proin=leo&leo=rhoncus&odio=sed&porttitor=vestibulum&id=sit', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (28, 'Andalax', 14, 'RF Shielding', 'Keylex', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'https://mediafire.com/maecenas.jsp?rhoncus=sagittis&aliquet=nam&pulvinar=congue&sed=risus&nisl=semper&nunc=porta&rhoncus=volutpat&dui=quam&vel=pede&sem=lobortis&sed=ligula&sagittis=sit&nam=amet&congue=eleifend&risus=pede&semper=libero&porta=quis&volutpat=orci&quam=nullam&pede=molestie&lobortis=nibh&ligula=in&sit=lectus&amet=pellentesque&eleifend=at&pede=nulla&libero=suspendisse&quis=potenti&orci=cras&nullam=in&molestie=purus&nibh=eu&in=magna&lectus=vulputate&pellentesque=luctus&at=cum&nulla=sociis&suspendisse=natoque&potenti=penatibus&cras=et&in=magnis&purus=dis&eu=parturient&magna=montes&vulputate=nascetur&luctus=ridiculus&cum=mus&sociis=vivamus&natoque=vestibulum&penatibus=sagittis&et=sapien&magnis=cum&dis=sociis&parturient=natoque&montes=penatibus&nascetur=et&ridiculus=magnis&mus=dis&vivamus=parturient&vestibulum=montes&sagittis=nascetur&sapien=ridiculus&cum=mus&sociis=etiam&natoque=vel&penatibus=augue&et=vestibulum&magnis=rutrum&dis=rutrum&parturient=neque&montes=aenean&nascetur=auctor&ridiculus=gravida&mus=sem&etiam=praesent&vel=id&augue=massa&vestibulum=id&rutrum=nisl&rutrum=venenatis&neque=lacinia&aenean=aenean&auctor=sit&gravida=amet&sem=justo&praesent=morbi&id=ut&massa=odio&id=cras&nisl=mi&venenatis=pede&lacinia=malesuada&aenean=in&sit=imperdiet&amet=et&justo=commodo&morbi=vulputate&ut=justo&odio=in&cras=blandit', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (29, 'Fintone', 5, 'Masonry', 'Cardify', 'Aenean fermentum. Donec ut mauris eget massa tempor convallis. Nulla neque libero, convallis eget, eleifend luctus, ultricies eu, nibh.', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.

Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.', 'http://arizona.edu/ut/massa/volutpat/convallis/morbi/odio/odio.png?odio=sollicitudin&porttitor=ut&id=suscipit&consequat=a&in=feugiat&consequat=et&ut=eros&nulla=vestibulum&sed=ac&accumsan=est&felis=lacinia&ut=nisi&at=venenatis&dolor=tristique&quis=fusce&odio=congue&consequat=diam&varius=id&integer=ornare&ac=imperdiet&leo=sapien&pellentesque=urna&ultrices=pretium&mattis=nisl&odio=ut&donec=volutpat&vitae=sapien&nisi=arcu&nam=sed&ultrices=augue&libero=aliquam&non=erat&mattis=volutpat&pulvinar=in&nulla=congue&pede=etiam&ullamcorper=justo&augue=etiam&a=pretium&suscipit=iaculis&nulla=justo&elit=in&ac=hac&nulla=habitasse&sed=platea&vel=dictumst&enim=etiam&sit=faucibus&amet=cursus&nunc=urna&viverra=ut&dapibus=tellus&nulla=nulla', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (30, 'Opela', 65, 'Ornamental Railings', 'Fixflex', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.', 'Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'http://whitehouse.gov/potenti/in/eleifend/quam/a/odio.aspx?turpis=convallis&eget=tortor&elit=risus&sodales=dapibus&scelerisque=augue&mauris=vel&sit=accumsan&amet=tellus&eros=nisi&suspendisse=eu&accumsan=orci&tortor=mauris&quis=lacinia&turpis=sapien&sed=quis&ante=libero&vivamus=nullam&tortor=sit&duis=amet&mattis=turpis&egestas=elementum&metus=ligula&aenean=vehicula&fermentum=consequat&donec=morbi&ut=a&mauris=ipsum&eget=integer&massa=a&tempor=nibh&convallis=in&nulla=quis&neque=justo&libero=maecenas&convallis=rhoncus&eget=aliquam', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (31, 'Tampflex', 69, 'RF Shielding', 'Otcom', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.

Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'https://berkeley.edu/turpis/elementum/ligula/vehicula/consequat/morbi/a.js?nullam=tempus&varius=vel&nulla=pede&facilisi=morbi&cras=porttitor&non=lorem&velit=id&nec=ligula&nisi=suspendisse&vulputate=ornare&nonummy=consequat&maecenas=lectus&tincidunt=in&lacus=est&at=risus&velit=auctor&vivamus=sed&vel=tristique&nulla=in&eget=tempus&eros=sit&elementum=amet&pellentesque=sem&quisque=fusce&porta=consequat&volutpat=nulla&erat=nisl&quisque=nunc&erat=nisl&eros=duis&viverra=bibendum&eget=felis&congue=sed&eget=interdum&semper=venenatis&rutrum=turpis&nulla=enim&nunc=blandit&purus=mi&phasellus=in&in=porttitor&felis=pede&donec=justo&semper=eu&sapien=massa&a=donec&libero=dapibus&nam=duis&dui=at&proin=velit&leo=eu&odio=est&porttitor=congue&id=elementum&consequat=in&in=hac&consequat=habitasse&ut=platea&nulla=dictumst&sed=morbi&accumsan=vestibulum&felis=velit&ut=id&at=pretium&dolor=iaculis&quis=diam&odio=erat&consequat=fermentum&varius=justo&integer=nec&ac=condimentum&leo=neque&pellentesque=sapien&ultrices=placerat&mattis=ante&odio=nulla&donec=justo&vitae=aliquam&nisi=quis&nam=turpis&ultrices=eget&libero=elit&non=sodales&mattis=scelerisque&pulvinar=mauris&nulla=sit&pede=amet&ullamcorper=eros&augue=suspendisse&a=accumsan&suscipit=tortor&nulla=quis', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (32, 'Alpha', 6, 'Fire Protection', 'Cookley', 'Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.', 'https://java.com/lacinia/erat/vestibulum/sed.html?mus=mi&etiam=integer&vel=ac&augue=neque&vestibulum=duis&rutrum=bibendum&rutrum=morbi&neque=non&aenean=quam&auctor=nec&gravida=dui&sem=luctus&praesent=rutrum&id=nulla&massa=tellus&id=in&nisl=sagittis&venenatis=dui&lacinia=vel&aenean=nisl&sit=duis&amet=ac&justo=nibh&morbi=fusce&ut=lacus&odio=purus&cras=aliquet&mi=at&pede=feugiat&malesuada=non&in=pretium&imperdiet=quis&et=lectus&commodo=suspendisse&vulputate=potenti&justo=in&in=eleifend&blandit=quam&ultrices=a&enim=odio&lorem=in&ipsum=hac&dolor=habitasse&sit=platea&amet=dictumst&consectetuer=maecenas&adipiscing=ut&elit=massa&proin=quis&interdum=augue&mauris=luctus&non=tincidunt&ligula=nulla&pellentesque=mollis&ultrices=molestie&phasellus=lorem&id=quisque&sapien=ut&in=erat&sapien=curabitur&iaculis=gravida&congue=nisi&vivamus=at&metus=nibh&arcu=in&adipiscing=hac&molestie=habitasse&hendrerit=platea&at=dictumst&vulputate=aliquam&vitae=augue&nisl=quam&aenean=sollicitudin&lectus=vitae&pellentesque=consectetuer', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (33, 'Lotstring', 95, 'Masonry', 'Prodder', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.', 'Vestibulum ac est lacinia nisi venenatis tristique. Fusce congue, diam id ornare imperdiet, sapien urna pretium nisl, ut volutpat sapien arcu sed augue. Aliquam erat volutpat.

In congue. Etiam justo. Etiam pretium iaculis justo.

In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'https://ftc.gov/mauris/morbi/non.html?molestie=tortor&nibh=sollicitudin&in=mi&lectus=sit&pellentesque=amet&at=lobortis&nulla=sapien&suspendisse=sapien&potenti=non&cras=mi&in=integer&purus=ac&eu=neque&magna=duis&vulputate=bibendum&luctus=morbi&cum=non&sociis=quam&natoque=nec&penatibus=dui&et=luctus&magnis=rutrum&dis=nulla&parturient=tellus&montes=in&nascetur=sagittis&ridiculus=dui&mus=vel&vivamus=nisl&vestibulum=duis&sagittis=ac&sapien=nibh&cum=fusce&sociis=lacus&natoque=purus&penatibus=aliquet&et=at&magnis=feugiat&dis=non&parturient=pretium&montes=quis&nascetur=lectus&ridiculus=suspendisse&mus=potenti&etiam=in&vel=eleifend&augue=quam&vestibulum=a&rutrum=odio&rutrum=in&neque=hac&aenean=habitasse&auctor=platea&gravida=dictumst&sem=maecenas&praesent=ut&id=massa&massa=quis&id=augue&nisl=luctus&venenatis=tincidunt&lacinia=nulla&aenean=mollis&sit=molestie&amet=lorem&justo=quisque&morbi=ut&ut=erat&odio=curabitur&cras=gravida&mi=nisi&pede=at&malesuada=nibh&in=in&imperdiet=hac&et=habitasse&commodo=platea&vulputate=dictumst&justo=aliquam&in=augue&blandit=quam&ultrices=sollicitudin&enim=vitae&lorem=consectetuer&ipsum=eget&dolor=rutrum&sit=at&amet=lorem&consectetuer=integer&adipiscing=tincidunt&elit=ante&proin=vel&interdum=ipsum&mauris=praesent&non=blandit&ligula=lacinia&pellentesque=erat&ultrices=vestibulum&phasellus=sed', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (34, 'Wrapsafe', 87, 'EIFS', 'Fixflex', 'Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'https://economist.com/mattis/egestas/metus/aenean.jpg?eros=leo&suspendisse=maecenas', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (35, 'Cardify', 57, 'Asphalt Paving', 'Lotstring', 'Curabitur in libero ut massa volutpat convallis. Morbi odio odio, elementum eu, interdum eu, tincidunt in, leo. Maecenas pulvinar lobortis est.', 'Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'http://vistaprint.com/luctus/et/ultrices/posuere/cubilia.jpg?maecenas=nunc&tincidunt=proin&lacus=at&at=turpis&velit=a&vivamus=pede&vel=posuere&nulla=nonummy&eget=integer&eros=non&elementum=velit&pellentesque=donec&quisque=diam&porta=neque&volutpat=vestibulum&erat=eget&quisque=vulputate&erat=ut&eros=ultrices&viverra=vel&eget=augue&congue=vestibulum&eget=ante&semper=ipsum&rutrum=primis&nulla=in&nunc=faucibus&purus=orci&phasellus=luctus&in=et&felis=ultrices&donec=posuere&semper=cubilia&sapien=curae&a=donec&libero=pharetra&nam=magna&dui=vestibulum&proin=aliquet&leo=ultrices&odio=erat&porttitor=tortor&id=sollicitudin&consequat=mi&in=sit&consequat=amet&ut=lobortis&nulla=sapien&sed=sapien&accumsan=non&felis=mi&ut=integer&at=ac&dolor=neque&quis=duis&odio=bibendum&consequat=morbi&varius=non&integer=quam&ac=nec&leo=dui&pellentesque=luctus&ultrices=rutrum&mattis=nulla&odio=tellus&donec=in&vitae=sagittis&nisi=dui&nam=vel&ultrices=nisl&libero=duis&non=ac&mattis=nibh&pulvinar=fusce&nulla=lacus&pede=purus&ullamcorper=aliquet&augue=at&a=feugiat&suscipit=non&nulla=pretium&elit=quis&ac=lectus&nulla=suspendisse&sed=potenti&vel=in&enim=eleifend&sit=quam', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (36, 'Aerified', 61, 'Drilled Shafts', 'Vagram', 'Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.', 'In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'https://si.edu/in/faucibus/orci/luctus.png?tellus=sapien&in=varius&sagittis=ut&dui=blandit&vel=non&nisl=interdum&duis=in&ac=ante&nibh=vestibulum&fusce=ante&lacus=ipsum&purus=primis&aliquet=in&at=faucibus&feugiat=orci&non=luctus&pretium=et&quis=ultrices&lectus=posuere&suspendisse=cubilia&potenti=curae&in=duis&eleifend=faucibus&quam=accumsan&a=odio&odio=curabitur&in=convallis&hac=duis&habitasse=consequat&platea=dui&dictumst=nec&maecenas=nisi&ut=volutpat&massa=eleifend&quis=donec&augue=ut&luctus=dolor&tincidunt=morbi&nulla=vel&mollis=lectus&molestie=in&lorem=quam&quisque=fringilla&ut=rhoncus', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (37, 'Bigtax', 6, 'Fire Sprinkler System', 'Sonair', 'Nam ultrices, libero non mattis pulvinar, nulla pede ullamcorper augue, a suscipit nulla elit ac nulla. Sed vel enim sit amet nunc viverra dapibus. Nulla suscipit ligula in lacus.', 'Nulla ut erat id mauris vulputate elementum. Nullam varius. Nulla facilisi.

Cras non velit nec nisi vulputate nonummy. Maecenas tincidunt lacus at velit. Vivamus vel nulla eget eros elementum pellentesque.

Quisque porta volutpat erat. Quisque erat eros, viverra eget, congue eget, semper rutrum, nulla. Nunc purus.', 'http://opera.com/sit/amet/eleifend/pede/libero/quis/orci.json?pellentesque=quam&quisque=pede&porta=lobortis&volutpat=ligula&erat=sit&quisque=amet&erat=eleifend&eros=pede&viverra=libero&eget=quis&congue=orci&eget=nullam&semper=molestie&rutrum=nibh&nulla=in&nunc=lectus&purus=pellentesque&phasellus=at&in=nulla&felis=suspendisse&donec=potenti&semper=cras&sapien=in&a=purus&libero=eu&nam=magna&dui=vulputate&proin=luctus&leo=cum', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (38, 'Pannier', 97, 'Roofing (Asphalt)', 'Home Ing', 'Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.

Praesent blandit. Nam nulla. Integer pede justo, lacinia eget, tincidunt eget, tempus vel, pede.', 'https://harvard.edu/neque/duis/bibendum/morbi/non.js?lectus=quisque&pellentesque=id&at=justo&nulla=sit&suspendisse=amet&potenti=sapien&cras=dignissim&in=vestibulum&purus=vestibulum&eu=ante&magna=ipsum&vulputate=primis&luctus=in&cum=faucibus&sociis=orci&natoque=luctus&penatibus=et&et=ultrices&magnis=posuere&dis=cubilia&parturient=curae&montes=nulla&nascetur=dapibus&ridiculus=dolor&mus=vel&vivamus=est&vestibulum=donec', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (39, 'Bigtax', 46, 'Ornamental Railings', 'Rank', 'Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.

Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'http://kickstarter.com/libero/convallis/eget/eleifend/luctus/ultricies.json?feugiat=diam&non=neque&pretium=vestibulum&quis=eget&lectus=vulputate&suspendisse=ut&potenti=ultrices&in=vel&eleifend=augue&quam=vestibulum&a=ante&odio=ipsum&in=primis&hac=in&habitasse=faucibus&platea=orci', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (40, 'Mat Lam Tam', 6, 'Rebar & Wire Mesh Install', 'Viva', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.

Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.', 'https://reuters.com/libero/non/mattis/pulvinar.json?cubilia=massa&curae=id&duis=nisl&faucibus=venenatis&accumsan=lacinia&odio=aenean&curabitur=sit&convallis=amet&duis=justo&consequat=morbi&dui=ut&nec=odio&nisi=cras&volutpat=mi&eleifend=pede&donec=malesuada', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (41, 'Solarbreeze', 4, 'Overhead Doors', 'Fintone', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Phasellus in felis. Donec semper sapien a libero. Nam dui.

Proin leo odio, porttitor id, consequat in, consequat ut, nulla. Sed accumsan felis. Ut at dolor quis odio consequat varius.

Integer ac leo. Pellentesque ultrices mattis odio. Donec vitae nisi.', 'http://fema.gov/at/velit.html?odio=ligula&in=in&hac=lacus&habitasse=curabitur&platea=at&dictumst=ipsum&maecenas=ac&ut=tellus&massa=semper&quis=interdum&augue=mauris&luctus=ullamcorper&tincidunt=purus', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (42, 'Zoolab', 60, 'Drywall & Acoustical (MOB)', 'Stim', 'Vestibulum quam sapien, varius ut, blandit non, interdum in, ante. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Duis faucibus accumsan odio. Curabitur convallis.', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'https://cdbaby.com/amet/nulla/quisque/arcu/libero/rutrum/ac.aspx?pellentesque=sagittis&ultrices=dui&phasellus=vel&id=nisl&sapien=duis&in=ac&sapien=nibh&iaculis=fusce&congue=lacus&vivamus=purus&metus=aliquet&arcu=at&adipiscing=feugiat&molestie=non&hendrerit=pretium&at=quis&vulputate=lectus&vitae=suspendisse&nisl=potenti&aenean=in&lectus=eleifend&pellentesque=quam&eget=a&nunc=odio&donec=in&quis=hac&orci=habitasse&eget=platea&orci=dictumst&vehicula=maecenas&condimentum=ut&curabitur=massa&in=quis&libero=augue&ut=luctus&massa=tincidunt&volutpat=nulla&convallis=mollis&morbi=molestie&odio=lorem&odio=quisque&elementum=ut&eu=erat&interdum=curabitur&eu=gravida&tincidunt=nisi&in=at&leo=nibh&maecenas=in&pulvinar=hac&lobortis=habitasse&est=platea&phasellus=dictumst&sit=aliquam&amet=augue&erat=quam&nulla=sollicitudin&tempus=vitae&vivamus=consectetuer&in=eget&felis=rutrum&eu=at&sapien=lorem&cursus=integer&vestibulum=tincidunt&proin=ante&eu=vel&mi=ipsum&nulla=praesent&ac=blandit&enim=lacinia', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (43, 'Kanlam', 41, 'Fire Sprinkler System', 'Cardguard', 'Duis aliquam convallis nunc. Proin at turpis a pede posuere nonummy. Integer non velit.', 'Mauris enim leo, rhoncus sed, vestibulum sit amet, cursus id, turpis. Integer aliquet, massa id lobortis convallis, tortor risus dapibus augue, vel accumsan tellus nisi eu orci. Mauris lacinia sapien quis libero.

Nullam sit amet turpis elementum ligula vehicula consequat. Morbi a ipsum. Integer a nibh.

In quis justo. Maecenas rhoncus aliquam lacus. Morbi quis tortor id nulla ultrices aliquet.', 'http://icio.us/suscipit/ligula/in/lacus/curabitur/at/ipsum.aspx?tortor=morbi&duis=a&mattis=ipsum&egestas=integer&metus=a&aenean=nibh&fermentum=in&donec=quis&ut=justo&mauris=maecenas&eget=rhoncus&massa=aliquam&tempor=lacus&convallis=morbi&nulla=quis&neque=tortor&libero=id&convallis=nulla&eget=ultrices&eleifend=aliquet&luctus=maecenas&ultricies=leo&eu=odio&nibh=condimentum&quisque=id&id=luctus&justo=nec&sit=molestie&amet=sed&sapien=justo&dignissim=pellentesque&vestibulum=viverra&vestibulum=pede&ante=ac&ipsum=diam&primis=cras&in=pellentesque&faucibus=volutpat&orci=dui&luctus=maecenas&et=tristique&ultrices=est&posuere=et&cubilia=tempus&curae=semper&nulla=est&dapibus=quam&dolor=pharetra&vel=magna&est=ac&donec=consequat&odio=metus&justo=sapien&sollicitudin=ut&ut=nunc&suscipit=vestibulum&a=ante&feugiat=ipsum&et=primis&eros=in&vestibulum=faucibus&ac=orci&est=luctus&lacinia=et&nisi=ultrices&venenatis=posuere&tristique=cubilia&fusce=curae&congue=mauris&diam=viverra&id=diam&ornare=vitae&imperdiet=quam&sapien=suspendisse&urna=potenti&pretium=nullam', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (44, 'Home Ing', 48, 'Framing (Wood)', 'Cardify', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Nullam porttitor lacus at turpis. Donec posuere metus vitae ipsum. Aliquam non mauris.

Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'http://1688.com/vivamus/in/felis/eu/sapien/cursus.js?curae=dolor&mauris=vel&viverra=est&diam=donec&vitae=odio&quam=justo&suspendisse=sollicitudin&potenti=ut&nullam=suscipit&porttitor=a&lacus=feugiat&at=et&turpis=eros&donec=vestibulum&posuere=ac&metus=est&vitae=lacinia&ipsum=nisi&aliquam=venenatis&non=tristique&mauris=fusce&morbi=congue&non=diam&lectus=id&aliquam=ornare&sit=imperdiet&amet=sapien&diam=urna&in=pretium&magna=nisl&bibendum=ut&imperdiet=volutpat&nullam=sapien&orci=arcu&pede=sed&venenatis=augue&non=aliquam', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (45, 'Sonair', 92, 'Drywall & Acoustical (MOB)', 'Span', 'Quisque id justo sit amet sapien dignissim vestibulum. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia Curae; Nulla dapibus dolor vel est. Donec odio justo, sollicitudin ut, suscipit a, feugiat et, eros.', 'In sagittis dui vel nisl. Duis ac nibh. Fusce lacus purus, aliquet at, feugiat non, pretium quis, lectus.

Suspendisse potenti. In eleifend quam a odio. In hac habitasse platea dictumst.

Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.', 'http://wiley.com/sollicitudin/ut/suscipit/a/feugiat.html?imperdiet=vestibulum&nullam=velit&orci=id&pede=pretium&venenatis=iaculis&non=diam&sodales=erat&sed=fermentum&tincidunt=justo&eu=nec&felis=condimentum&fusce=neque&posuere=sapien&felis=placerat&sed=ante&lacus=nulla&morbi=justo&sem=aliquam&mauris=quis&laoreet=turpis&ut=eget&rhoncus=elit&aliquet=sodales&pulvinar=scelerisque&sed=mauris&nisl=sit&nunc=amet&rhoncus=eros&dui=suspendisse&vel=accumsan&sem=tortor&sed=quis&sagittis=turpis&nam=sed&congue=ante&risus=vivamus&semper=tortor&porta=duis&volutpat=mattis&quam=egestas&pede=metus&lobortis=aenean&ligula=fermentum&sit=donec&amet=ut&eleifend=mauris&pede=eget&libero=massa&quis=tempor&orci=convallis&nullam=nulla&molestie=neque&nibh=libero&in=convallis&lectus=eget&pellentesque=eleifend&at=luctus&nulla=ultricies&suspendisse=eu&potenti=nibh&cras=quisque&in=id&purus=justo&eu=sit&magna=amet&vulputate=sapien&luctus=dignissim&cum=vestibulum&sociis=vestibulum&natoque=ante&penatibus=ipsum&et=primis&magnis=in&dis=faucibus&parturient=orci&montes=luctus&nascetur=et', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (46, 'Vagram', 20, 'Structural & Misc Steel Erection', 'Cardguard', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.', 'Maecenas ut massa quis augue luctus tincidunt. Nulla mollis molestie lorem. Quisque ut erat.

Curabitur gravida nisi at nibh. In hac habitasse platea dictumst. Aliquam augue quam, sollicitudin vitae, consectetuer eget, rutrum at, lorem.

Integer tincidunt ante vel ipsum. Praesent blandit lacinia erat. Vestibulum sed magna at nunc commodo placerat.', 'https://alibaba.com/sed.aspx?dapibus=posuere&dolor=cubilia&vel=curae&est=nulla&donec=dapibus&odio=dolor&justo=vel&sollicitudin=est&ut=donec&suscipit=odio&a=justo&feugiat=sollicitudin&et=ut&eros=suscipit&vestibulum=a&ac=feugiat&est=et&lacinia=eros&nisi=vestibulum&venenatis=ac&tristique=est&fusce=lacinia&congue=nisi&diam=venenatis&id=tristique&ornare=fusce', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (47, 'Span', 92, 'Roofing (Asphalt)', 'Tin', 'Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.

Cras mi pede, malesuada in, imperdiet et, commodo vulputate, justo. In blandit ultrices enim. Lorem ipsum dolor sit amet, consectetuer adipiscing elit.

Proin interdum mauris non ligula pellentesque ultrices. Phasellus id sapien in sapien iaculis congue. Vivamus metus arcu, adipiscing molestie, hendrerit at, vulputate vitae, nisl.', 'http://slate.com/augue/a/suscipit/nulla/elit.jsp?odio=rhoncus&justo=dui&sollicitudin=vel&ut=sem&suscipit=sed&a=sagittis&feugiat=nam&et=congue&eros=risus&vestibulum=semper&ac=porta&est=volutpat&lacinia=quam&nisi=pede&venenatis=lobortis&tristique=ligula&fusce=sit&congue=amet&diam=eleifend&id=pede&ornare=libero&imperdiet=quis&sapien=orci&urna=nullam&pretium=molestie&nisl=nibh&ut=in&volutpat=lectus&sapien=pellentesque&arcu=at&sed=nulla&augue=suspendisse&aliquam=potenti&erat=cras&volutpat=in&in=purus&congue=eu&etiam=magna&justo=vulputate&etiam=luctus&pretium=cum&iaculis=sociis&justo=natoque&in=penatibus&hac=et&habitasse=magnis&platea=dis&dictumst=parturient&etiam=montes', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (48, 'Tin', 79, 'Drilled Shafts', 'Tres-Zap', 'In congue. Etiam justo. Etiam pretium iaculis justo.', 'Pellentesque at nulla. Suspendisse potenti. Cras in purus eu magna vulputate luctus.

Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Vivamus vestibulum sagittis sapien. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus.', 'https://msn.com/vel.aspx?primis=imperdiet&in=sapien&faucibus=urna&orci=pretium&luctus=nisl&et=ut&ultrices=volutpat&posuere=sapien&cubilia=arcu&curae=sed&nulla=augue&dapibus=aliquam&dolor=erat&vel=volutpat&est=in&donec=congue&odio=etiam&justo=justo&sollicitudin=etiam&ut=pretium&suscipit=iaculis&a=justo&feugiat=in&et=hac&eros=habitasse&vestibulum=platea&ac=dictumst&est=etiam&lacinia=faucibus&nisi=cursus&venenatis=urna&tristique=ut&fusce=tellus&congue=nulla&diam=ut&id=erat&ornare=id&imperdiet=mauris&sapien=vulputate&urna=elementum&pretium=nullam&nisl=varius&ut=nulla&volutpat=facilisi&sapien=cras&arcu=non&sed=velit&augue=nec&aliquam=nisi&erat=vulputate&volutpat=nonummy&in=maecenas&congue=tincidunt&etiam=lacus&justo=at&etiam=velit&pretium=vivamus&iaculis=vel&justo=nulla&in=eget&hac=eros&habitasse=elementum&platea=pellentesque&dictumst=quisque&etiam=porta&faucibus=volutpat&cursus=erat&urna=quisque&ut=erat&tellus=eros&nulla=viverra&ut=eget&erat=congue&id=eget&mauris=semper&vulputate=rutrum&elementum=nulla&nullam=nunc&varius=purus&nulla=phasellus', false);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (49, 'Prodder', 35, 'Drilled Shafts', 'Gembucket', 'In hac habitasse platea dictumst. Etiam faucibus cursus urna. Ut tellus.', 'Duis bibendum, felis sed interdum venenatis, turpis enim blandit mi, in porttitor pede justo eu massa. Donec dapibus. Duis at velit eu est congue elementum.

In hac habitasse platea dictumst. Morbi vestibulum, velit id pretium iaculis, diam erat fermentum justo, nec condimentum neque sapien placerat ante. Nulla justo.

Aliquam quis turpis eget elit sodales scelerisque. Mauris sit amet eros. Suspendisse accumsan tortor quis turpis.', 'https://elpais.com/cum/sociis/natoque/penatibus/et.jsp?mi=lacinia&sit=aenean&amet=sit&lobortis=amet&sapien=justo&sapien=morbi&non=ut&mi=odio&integer=cras&ac=mi&neque=pede&duis=malesuada&bibendum=in&morbi=imperdiet&non=et&quam=commodo&nec=vulputate&dui=justo&luctus=in&rutrum=blandit&nulla=ultrices&tellus=enim&in=lorem&sagittis=ipsum&dui=dolor&vel=sit&nisl=amet&duis=consectetuer&ac=adipiscing&nibh=elit&fusce=proin&lacus=interdum&purus=mauris&aliquet=non&at=ligula&feugiat=pellentesque&non=ultrices&pretium=phasellus&quis=id&lectus=sapien&suspendisse=in&potenti=sapien&in=iaculis&eleifend=congue&quam=vivamus&a=metus&odio=arcu&in=adipiscing&hac=molestie&habitasse=hendrerit&platea=at&dictumst=vulputate&maecenas=vitae&ut=nisl&massa=aenean&quis=lectus&augue=pellentesque&luctus=eget&tincidunt=nunc&nulla=donec&mollis=quis&molestie=orci&lorem=eget&quisque=orci&ut=vehicula&erat=condimentum&curabitur=curabitur&gravida=in&nisi=libero&at=ut&nibh=massa&in=volutpat&hac=convallis&habitasse=morbi&platea=odio', true);
insert into products (id, name, price, category, apptype, short_description, description, stripe_link, available) values (50, 'Flowdesk', 26, 'Structural and Misc Steel (Fabrication)', 'Matsoft', 'Morbi non lectus. Aliquam sit amet diam in magna bibendum imperdiet. Nullam orci pede, venenatis non, sodales sed, tincidunt eu, felis.', 'Etiam vel augue. Vestibulum rutrum rutrum neque. Aenean auctor gravida sem.

Praesent id massa id nisl venenatis lacinia. Aenean sit amet justo. Morbi ut odio.', 'http://dell.com/magna/vestibulum/aliquet/ultrices.jsp?placerat=vivamus&praesent=metus&blandit=arcu&nam=adipiscing&nulla=molestie&integer=hendrerit&pede=at&justo=vulputate&lacinia=vitae&eget=nisl', true);
