insert into teammembers (id, name, position, is_collab) values (1, 'Richardo Cuerdale', 'Geological Engineer', true);
insert into teammembers (id, name, position, is_collab) values (2, 'Josh Gostall', 'Sales Associate', false);
insert into teammembers (id, name, position, is_collab) values (3, 'Margit Corkitt', 'Account Executive', true);
insert into teammembers (id, name, position, is_collab) values (4, 'Thelma Attryde', 'Assistant Manager', false);
insert into teammembers (id, name, position, is_collab) values (5, 'Reynard Reston', 'Research Nurse', false);
insert into teammembers (id, name, position, is_collab) values (6, 'Daune Raccio', 'Biostatistician I', true);
insert into teammembers (id, name, position, is_collab) values (7, 'Gabbey Santo', 'VP Marketing', true);
insert into teammembers (id, name, position, is_collab) values (8, 'Antonina Harrop', 'Mechanical Systems Engineer', true);
insert into teammembers (id, name, position, is_collab) values (9, 'Dan Dauber', 'Pharmacist', false);
insert into teammembers (id, name, position, is_collab) values (10, 'Town Bantham', 'Payment Adjustment Coordinator', true);
insert into teammembers (id, name, position, is_collab) values (11, 'Bertina Priel', 'Actuary', true);
insert into teammembers (id, name, position, is_collab) values (12, 'Brade Lumby', 'Database Administrator III', false);
insert into teammembers (id, name, position, is_collab) values (13, 'Hebert Shaxby', 'Automation Specialist III', true);
insert into teammembers (id, name, position, is_collab) values (14, 'Sonja Nockells', 'Nuclear Power Engineer', true);
insert into teammembers (id, name, position, is_collab) values (15, 'Sisile Georg', 'Budget/Accounting Analyst III', false);
insert into teammembers (id, name, position, is_collab) values (16, 'Adeline Baszkiewicz', 'Mechanical Systems Engineer', true);
insert into teammembers (id, name, position, is_collab) values (17, 'Koenraad Pancoast', 'Assistant Media Planner', false);
insert into teammembers (id, name, position, is_collab) values (18, 'Wylie Bisson', 'Senior Cost Accountant', true);
insert into teammembers (id, name, position, is_collab) values (19, 'Geri Sokale', 'Recruiting Manager', false);
insert into teammembers (id, name, position, is_collab) values (20, 'Ivette Ratnege', 'Quality Engineer', true);
insert into teammembers (id, name, position, is_collab) values (21, 'Almira Ambrogi', 'Health Coach II', true);
insert into teammembers (id, name, position, is_collab) values (22, 'Christian Joinsey', 'Administrative Officer', true);
insert into teammembers (id, name, position, is_collab) values (23, 'Nanon Jorio', 'Senior Financial Analyst', true);
insert into teammembers (id, name, position, is_collab) values (24, 'Lark Ace', 'VP Marketing', true);
insert into teammembers (id, name, position, is_collab) values (25, 'Nadia Gother', 'Paralegal', false);
insert into teammembers (id, name, position, is_collab) values (26, 'Ricca Hallihane', 'Business Systems Development Analyst', true);
insert into teammembers (id, name, position, is_collab) values (27, 'Idaline Novakovic', 'Statistician III', true);
insert into teammembers (id, name, position, is_collab) values (28, 'Lesley Furlow', 'Internal Auditor', false);
insert into teammembers (id, name, position, is_collab) values (29, 'Nathanil Boate', 'Geological Engineer', false);
insert into teammembers (id, name, position, is_collab) values (30, 'Jillian Gosnall', 'Financial Advisor', false);
insert into teammembers (id, name, position, is_collab) values (31, 'Cynthea Hearnaman', 'Accountant IV', true);
insert into teammembers (id, name, position, is_collab) values (32, 'Manon Catonnet', 'VP Marketing', false);
insert into teammembers (id, name, position, is_collab) values (33, 'Kendricks Morritt', 'Programmer IV', true);
insert into teammembers (id, name, position, is_collab) values (34, 'Kathryn Brumwell', 'Social Worker', false);
insert into teammembers (id, name, position, is_collab) values (35, 'Reggie Halbeard', 'Technical Writer', false);
insert into teammembers (id, name, position, is_collab) values (36, 'Ennis Entwhistle', 'Account Representative I', true);
insert into teammembers (id, name, position, is_collab) values (37, 'Johnathan Stronack', 'VP Marketing', true);
insert into teammembers (id, name, position, is_collab) values (38, 'Wiley Ruprecht', 'Developer II', true);
insert into teammembers (id, name, position, is_collab) values (39, 'Bobbee Edmead', 'Director of Sales', true);
insert into teammembers (id, name, position, is_collab) values (40, 'Powell Georgiev', 'Senior Sales Associate', true);
insert into teammembers (id, name, position, is_collab) values (41, 'Rickert Custard', 'Pharmacist', true);
insert into teammembers (id, name, position, is_collab) values (42, 'Kiley Edwin', 'Assistant Manager', false);
insert into teammembers (id, name, position, is_collab) values (43, 'Myrna Shrubshall', 'Structural Analysis Engineer', true);
insert into teammembers (id, name, position, is_collab) values (44, 'Torrance Slewcock', 'Office Assistant III', false);
insert into teammembers (id, name, position, is_collab) values (45, 'Margareta Jaggli', 'Paralegal', true);
insert into teammembers (id, name, position, is_collab) values (46, 'Alfy Hanvey', 'Research Nurse', true);
insert into teammembers (id, name, position, is_collab) values (47, 'Glory Boniface', 'Clinical Specialist', false);
insert into teammembers (id, name, position, is_collab) values (48, 'Jasper Santi', 'Social Worker', false);
insert into teammembers (id, name, position, is_collab) values (49, 'Gillan Dauncey', 'Clinical Specialist', false);
insert into teammembers (id, name, position, is_collab) values (50, 'Debbie Liddon', 'Programmer II', false);
