#[macro_use]
extern crate rocket;

#[macro_use]
extern crate diesel;

use dotenv::dotenv;
use rocket::serde::json::{json, Json, Value};
use std::env;

/* Crate modules */

// Database pool handling module
mod db;

// Database models + methods module
mod models;

// Database Schema autogenerated by Diesel
mod schema;

// Static file handler module
mod static_files;

// Testimonial Model routes
mod testimonial_routes;

// Project Routes
// FSProject Routes
// License Routes
// Hall Of Fame Routes
// Team Members Routes
// Privacy Policy Routes
// Terms Of Service Routes
// Blog Post Routes
// Product Routes

/* Universal 404 handler */
#[catch(404)]
pub fn not_found() -> Json<Value> {
    Json(json!({
        "status": "error",
        "reason": "Resource was not found"
    }))
}

#[launch]
fn rocket() -> _ {
    dotenv().ok();
    let db_url = env::var("DATABASE_URL").expect("set DATABASE_URL");
    let pool = db::init_pool(db_url);

    rocket::build()
        .manage(pool)
        .mount(
            "/api/v1/",
            routes![
                // Testimonial Routes
                crate::testimonial_routes::index,
                crate::testimonial_routes::new,
                crate::testimonial_routes::show,
                crate::testimonial_routes::delete,
                crate::testimonial_routes::author,
                crate::testimonial_routes::update,
                // Project Routes
                // FSProject Routes
                // License Routes
                // Hall Of Fame Routes
                // Team Members Routes
                // Privacy Policy Routes
                // Terms Of Service Routes
                // Blog Post Routes
                // Product Routes
            ],
        )
        .mount(
            "/",
            routes![crate::static_files::all, crate::static_files::index],
        )
}
